# 1.Print 'Hello HCIA'.

In [2]:
print("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [1]:
a = 23
b = 3
print(a + b)

26


# 3.Define a list and replicate in three different ways.

In [ ]:
A = [1, 2, 3, 4, 5]

# 4.Define two lists and merge them together.

In [3]:
A = [1, 2, 3]
B = [4, 5, 6]
print(A + B)

[1, 2, 3, 4, 5, 6]


# 5. Get the last element of the list and print it.

In [4]:
A = [1, 2, 4, 5, 6]
print(A[-1])

6


# 6.Define a tuple that contains only one element.

In [12]:
T = ("One element")
print(T)

One element


# 7.Define a three-line long string.

In [10]:
str ="""what
        a
        str"""
print(str)

what
        a
        f*ck


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [14]:
T = ("a", "b", "c", "d", "e", "f", "g")
for i in T:
    print(i, end = " ")

a b c d e f g 

# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [15]:
def Mul(a, b):
    return a*b
print(Mul(8, 6))

48


# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [19]:
import numpy
A = numpy.zeros((5,5))
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [20]:
import numpy
A = numpy.zeros((4,6))
print(A)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# 12.Use numpy.arange() to generate an array of shape(15,), then modify the shape to(3,5).

In [25]:
import numpy
A = numpy.arange(15,)
A = A.reshape(-3, 5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [28]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(A*B)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
